### ISSUE TITLE
[Bug] 파편 계산 시, 결과가 나오지 않는 버그

### ISSUE THREAD

**Issue by Parkjoungwan** [RGovernment/limbusCalculater#1]
![화면-기록-2023-06-03-오후-10 06 09-2](https://github.com/RGovernment/limbusCalculater/assets/48785968/d95f94c0-cfd1-4abd-b03c-3565dbdfe433)
파편 계산기로 전환 후, 주간 보너스 없음을 클릭한 후 계산을 누를 경우 결과가 나오지 않습니다.

**Comment by RGovernment** [comment]
오늘 올라오는 수정에 반영될 예정입니다. 바빠서 지금 수정하고 답을 해드리네요 죄송합니다 ㅠㅠ
